[package]
name = "redemption"
version = "0.0.0"
upgrade_policy = "immutable"

[addresses]
redemption = "0xCAFE"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
